#!/usr/bin/env bash
# check if all requirements are provided
if [ "$#" -ne 4 ]; then
    echo "usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit 1
fi

file_path="$1"
server_ip="$2"
username="$3"
ssh_key_path="$4"

# transfer the file file using scp, disable strict host key cheking
scp -o StrictHostKeyChecking=no -i
"$ssh_key_path" "$file_path" "$username@$server_ip:~/$1"

# check the exit status of the scp
if [ $? -eq 0]; then
    echo "File transfer successful."
else 
    echo "File transfer failed"
fi
