#!/usr/bin/env bash
# update package list and install nginx
sudo apt update
sudo apt install nginx -y

# check if nginx is installed successffully
if [ $? -eq 0 ]; then
    echo "Nginx installation successful"
else
    echo "Nginx installation failed. Exiting."
    exit 1
fi

# Confirm Nginx listening on port 80 and return hello world
echo 'Hello World!' | sudo tee /var/www/html/index.html

# test nginx config
sudo nginx -t

# if config test passes reload nginx to apply changes
if [ $? -eq 0 ]; then
    sudo nginx -s reload
    echo "Nginx configuration aplied and reload successfully."
else
    echo "Nginx configuration test failed. Changes not applied."
    exit 1
fi