#!/usr/bin/env bash
# Install and configure nginx

CONFIG_FILE="/etc/nginx/sites-available/default"

sudo apt update
sudo apt -y install nginx
sudo mkdir /etc/nginx/html
sudo touch /etc/nginx/html/index.html
sudo chmod +w /etc/nginx/html/index.html
sudo echo "Hello World!" | sudo tee /etc/nginx/html/index.html > /dev/null
sudo touch /etc/nginx/html/404_page.html
sudo chmod +w /etc/nginx/html/404_page.html
sudo echo "Ceci n'est pas une page" | sudo tee /etc/nginx/html/404_page.html > /dev/null
sudo echo "
server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /etc/nginx/html;
	index index.html index.htm;

	location /redirect_me {
        	return 301 http://thorbie.tech/;
    	}

	error_page 404 /404_page.html;
	location = /404_page.html {
        	root /etc/nginx/html;
        	internal;
    	}
}" | sudo tee /etc/nginx/sites-available/default > /dev/null
sudo nginx -t
sudo service nginx restart
