#!/usr/bin/env bash
#set the name of the private key
private key="school"

# set the number of bits for the private key
passphrase=4096

# generate the SSh key pair
ssh-keygen -t rsa -b "$key_bits" -f "$private_key" -N "$passphrase"