#!/usr/bin/env bash
#set the name of the private key
private_key="school"

# set the number of bits for the private key
key_bits=4096

#set the passphrase
passphrase="betty"

# generate the SSh key pair
ssh-keygen -t rsa -b "$key_bits" -f "$private_key" -N "$passphrase"
